/**
 * Planet-Sign Color Mapping
 *
 * This mapping defines the color for each planet based on the zodiac sign (1-12)
 * Colors are applied when rendering planets in the astrological grid
 */

// Planet names in Sinhala (as returned from the API)
export const PLANETS = {
  RA: 'ර',      // Ravi (Sun)
  CHA: 'ච',     // Chandra (Moon)
  KU: 'කු',     // Kuja (Mars)
  BU: 'බු',     // Budha (Mercury)
  GU: 'ගු',     // Guru (Jupiter)
  SHU: 'ශු',    // Shukra (Venus)
  SHA: 'ශ',     // Shani (Saturn)
  RAA: 'රා',    // Rahu
  KE: 'කේ',     // Ketu
} as const;

// Color definitions
export const PLANET_COLORS = {
  DARK_GREEN: '#006400',
  GREEN: '#008000',
  SADDLE_BROWN: '#8B4513',
  BLUE: '#0000FF',
  DARK_GRAY: '#A9A9A9',
  RED: '#FF0000',
  DARK_ORANGE: '#FF8C00',
} as const;

// Planet-Sign color mapping table
// Rows: Signs 1-12 (රාශි අංකය)
// Columns: Planets (ර, ච, කු, බු, ගු, ශු, ශ, රා, කේ)
const PLANET_SIGN_COLOR_MAP: Record<number, Record<string, string>> = {
  1: {
    [PLANETS.RA]: PLANET_COLORS.BLUE,
    [PLANETS.CHA]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.KU]: PLANET_COLORS.DARK_GREEN,
    [PLANETS.BU]: PLANET_COLORS.DARK_GRAY,
    [PLANETS.GU]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.SHU]: PLANET_COLORS.DARK_ORANGE,
    [PLANETS.SHA]: PLANET_COLORS.RED,
    [PLANETS.RAA]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.KE]: PLANET_COLORS.SADDLE_BROWN,
  },
  2: {
    [PLANETS.RA]: PLANET_COLORS.DARK_GRAY,
    [PLANETS.CHA]: PLANET_COLORS.BLUE,
    [PLANETS.KU]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.BU]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.GU]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.SHU]: PLANET_COLORS.DARK_GREEN,
    [PLANETS.SHA]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.RAA]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.KE]: PLANET_COLORS.DARK_ORANGE,
  },
  3: {
    [PLANETS.RA]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.CHA]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.KU]: PLANET_COLORS.DARK_ORANGE,
    [PLANETS.BU]: PLANET_COLORS.DARK_GREEN,
    [PLANETS.GU]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.SHU]: PLANET_COLORS.DARK_GRAY,
    [PLANETS.SHA]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.RAA]: PLANET_COLORS.DARK_GREEN,
    [PLANETS.KE]: PLANET_COLORS.SADDLE_BROWN,
  },
  4: {
    [PLANETS.RA]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.CHA]: PLANET_COLORS.DARK_GREEN,
    [PLANETS.KU]: PLANET_COLORS.DARK_ORANGE,
    [PLANETS.BU]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.GU]: PLANET_COLORS.BLUE,
    [PLANETS.SHU]: PLANET_COLORS.DARK_GRAY,
    [PLANETS.SHA]: PLANET_COLORS.RED,
    [PLANETS.RAA]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.KE]: PLANET_COLORS.SADDLE_BROWN,
  },
  5: {
    [PLANETS.RA]: PLANET_COLORS.DARK_GREEN,
    [PLANETS.CHA]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.KU]: PLANET_COLORS.GREEN,
    [PLANETS.BU]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.GU]: PLANET_COLORS.DARK_GRAY,
    [PLANETS.SHU]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.SHA]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.RAA]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.KE]: PLANET_COLORS.SADDLE_BROWN,
  },
  6: {
    [PLANETS.RA]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.CHA]: PLANET_COLORS.DARK_GRAY,
    [PLANETS.KU]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.BU]: PLANET_COLORS.BLUE,
    [PLANETS.GU]: PLANET_COLORS.DARK_GREEN,
    [PLANETS.SHU]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.SHA]: PLANET_COLORS.DARK_GRAY,
    [PLANETS.RAA]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.KE]: PLANET_COLORS.SADDLE_BROWN,
  },
  7: {
    [PLANETS.RA]: PLANET_COLORS.RED,
    [PLANETS.CHA]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.KU]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.BU]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.GU]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.SHU]: PLANET_COLORS.DARK_GREEN,
    [PLANETS.SHA]: PLANET_COLORS.BLUE,
    [PLANETS.RAA]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.KE]: PLANET_COLORS.DARK_GREEN,
  },
  8: {
    [PLANETS.RA]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.CHA]: PLANET_COLORS.RED,
    [PLANETS.KU]: PLANET_COLORS.DARK_GREEN,
    [PLANETS.BU]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.GU]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.SHU]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.SHA]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.RAA]: PLANET_COLORS.DARK_GREEN,
    [PLANETS.KE]: PLANET_COLORS.SADDLE_BROWN,
  },
  9: {
    [PLANETS.RA]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.CHA]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.KU]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.BU]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.GU]: PLANET_COLORS.DARK_GREEN,
    [PLANETS.SHU]: PLANET_COLORS.BLUE,
    [PLANETS.SHA]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.RAA]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.KE]: PLANET_COLORS.SADDLE_BROWN,
  },
  10: {
    [PLANETS.RA]: PLANET_COLORS.RED,
    [PLANETS.CHA]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.KU]: PLANET_COLORS.BLUE,
    [PLANETS.BU]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.GU]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.SHU]: PLANET_COLORS.DARK_ORANGE,
    [PLANETS.SHA]: PLANET_COLORS.GREEN,
    [PLANETS.RAA]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.KE]: PLANET_COLORS.SADDLE_BROWN,
  },
  11: {
    [PLANETS.RA]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.CHA]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.KU]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.BU]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.GU]: PLANET_COLORS.DARK_ORANGE,
    [PLANETS.SHU]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.SHA]: PLANET_COLORS.GREEN,
    [PLANETS.RAA]: PLANET_COLORS.GREEN,
    [PLANETS.KE]: PLANET_COLORS.SADDLE_BROWN,
  },
  12: {
    [PLANETS.RA]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.CHA]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.KU]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.BU]: PLANET_COLORS.DARK_ORANGE,
    [PLANETS.GU]: PLANET_COLORS.DARK_GREEN,
    [PLANETS.SHU]: PLANET_COLORS.BLUE,
    [PLANETS.SHA]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.RAA]: PLANET_COLORS.SADDLE_BROWN,
    [PLANETS.KE]: PLANET_COLORS.GREEN,
  },
};

/**
 * Get the color for a planet based on its zodiac sign
 * @param planet - The planet name (in Sinhala)
 * @param sign - The zodiac sign number (1-12)
 * @returns The color hex code, or a default gray if not found
 */
export function getPlanetColor(planet: string, sign: number): string {
  // Validate sign is within range
  if (sign < 1 || sign > 12) {
    console.warn(`Invalid sign number: ${sign}. Must be between 1 and 12.`);
    return PLANET_COLORS.DARK_GRAY;
  }

  // Get the color from the mapping
  const signColors = PLANET_SIGN_COLOR_MAP[sign];
  if (!signColors) {
    console.warn(`No color mapping found for sign: ${sign}`);
    return PLANET_COLORS.DARK_GRAY;
  }

  const color = signColors[planet];
  if (!color) {
    console.warn(`No color mapping found for planet "${planet}" in sign ${sign}`);
    return PLANET_COLORS.DARK_GRAY;
  }

  return color;
}
